Nav_links:
  type: list
  default: "新帖;按话题创建时间排序;?order=created"
  description:
    en: "Semicolon delimited in this order: display name;description;URL. Display name is the text that shows on the menu. Description is the help text that shows on hover. URL is the path for the link."
Hide_dropdowns:
  default: false
  description:
    en: "Hide category and tag dropdowns"
Hide_default_links:
  default: false
  description:
    en: "Hide the default 'Latest' and 'Categories' links on both mobile and desktop. Some Discourse settings will need to be changed. See theme topic on Meta"
